import 'package:nearkart_delivery/core/models/delivery_order_model.dart';

class DeliveryDummyData {
  static final List<DeliveryOrder> orders = [
    DeliveryOrder(
      id: 'NK10023',
      customerName: 'Priya S.',
      customerPhone: '+91 98765 43210',
      pickupAddress: 'Fresh Mart, MG Road, Koramangala',
      deliveryAddress: '12, 5th Cross, Koramangala, Bengaluru',
      distance: 1.8, earnings: 35,
      items: ['Fresh Banana × 2', 'Whole Milk × 1'],
      status: DeliveryStatus.assigned,
      assignedAt: DateTime.now().subtract(const Duration(minutes: 3)),
      paymentMethod: 'Cash on Delivery',
    ),
    DeliveryOrder(
      id: 'NK10022',
      customerName: 'Rahul M.',
      customerPhone: '+91 91234 56789',
      pickupAddress: 'Fresh Mart, MG Road, Koramangala',
      deliveryAddress: '45, Indiranagar 2nd Stage, Bengaluru',
      distance: 3.2, earnings: 50,
      items: ['Red Apple × 1', 'Brown Bread × 2'],
      status: DeliveryStatus.onTheWay,
      assignedAt: DateTime.now().subtract(const Duration(minutes: 22)),
      paymentMethod: 'UPI',
    ),
    DeliveryOrder(
      id: 'NK10021',
      customerName: 'Ananya K.',
      customerPhone: '+91 87654 32109',
      pickupAddress: 'Green Basket, HSR Layout',
      deliveryAddress: '7, 27th Main, HSR Layout, Bengaluru',
      distance: 0.9, earnings: 25,
      items: ['Paneer × 2'],
      status: DeliveryStatus.delivered,
      assignedAt: DateTime.now().subtract(const Duration(hours: 1)),
      paymentMethod: 'UPI',
    ),
    DeliveryOrder(
      id: 'NK10020',
      customerName: 'Vikram R.',
      customerPhone: '+91 76543 21098',
      pickupAddress: 'Daily Needs, BTM Layout',
      deliveryAddress: '3, BTM 2nd Stage, Bengaluru',
      distance: 2.1, earnings: 40,
      items: ['Greek Yogurt × 1', 'Orange Juice × 2'],
      status: DeliveryStatus.delivered,
      assignedAt: DateTime.now().subtract(const Duration(hours: 2, minutes: 30)),
      paymentMethod: 'Card',
    ),
    DeliveryOrder(
      id: 'NK10019',
      customerName: 'Deepa N.',
      customerPhone: '+91 65432 10987',
      pickupAddress: 'Organic Hub, Whitefield',
      deliveryAddress: '22, Whitefield Main Rd, Bengaluru',
      distance: 1.5, earnings: 30,
      items: ['Dark Chocolate × 3'],
      status: DeliveryStatus.failed,
      assignedAt: DateTime.now().subtract(const Duration(hours: 4)),
      paymentMethod: 'Cash on Delivery',
    ),
  ];
}
